### ISSUE TITLE
Error while trying to launch app

### ISSUE THREAD

**Issue by OxoGhost01** [anetczuk/ClevoKeyboardControl#10]
Hey, i got this error while runny main.py : 
File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 258, in <listcomp>
    paths = [os.path.join(root, entry.name) for entry in self.listdir(root)]
                                ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

**Comment by anetczuk** [comment]
Hello, what is your version of watchdog package (mine is 2.19)? It seems that it is problem of some versions of the package.

**Comment by OxoGhost01** [comment]
Hello, sorry had a problem with my OS (had to reinstall it from scratch 😭 ). My watchdog version seems to be 2.2.1-1 (i'm on debian btw).

**Comment by anetczuk** [comment]
I made a typo in previous comment. Proper working version is 2.1.9, so downgrade the watchdog below 2.2

**Comment by OxoGhost01** [comment]
Got the same error, so maybe watchdog isn't the problem :/

here is the entire return : 

2025-02-04 21:42:01,497 DEBUG    MainThread __main__:main [main.py:85] Starting the application
2025-02-04 21:42:01,497 DEBUG    MainThread __main__:main [main.py:86] Logger log file: /home/oxoghost/Documents/ClevoKeyboardControl/tmp/log/log.txt
QSocketNotifier: Can only be used with threads started with QThread
2025-02-04 21:42:01,575 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:setEnabled [suspenddetector.py:127] changing suspend detector state to True
2025-02-04 21:42:01,576 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:134] starting suspension detector
2025-02-04 21:42:01,576 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:42] starting suspension timer
2025-02-04 21:42:01,576 DEBUG    MainThread clevokeyboardcontrol.screensaverwatcher.ScreenSaverWatcher:__init__ [screensaverwatcher.py:131] registering device watcher: /sys/class/backlight/intel_backlight
2025-02-04 21:42:01,576 ERROR    MainThread __main__:main [main.py:105] Exception occured
Traceback (most recent call last):
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/main.py", line 101, in main
    exitCode = runApp(args)
               ^^^^^^^^^^^^
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/main.py", line 59, in runApp
    window = MainWindow( driver )
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/gui/main_window.py", line 68, in __init__
    self.screenSaverDetector = screensaverwatcher.ScreenSaverWatcher()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/screensaverwatcher.py", line 132, in __init__
    watcher = DeviceWatcher( item_path, len(self.watchers) )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/screensaverwatcher.py", line 63, in __init__
    self.watcher.watch( self.driverPath, False )
  File "/home/oxoghost/Documents/ClevoKeyboardControl/src/clevokeyboardcontrol/sysfswatchdog.py", line 62, in watch
    self.observer.start()
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3/dist-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 76, in on_thread_start
    self._snapshot = self._take_snapshot()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 72, in <lambda>
    self._take_snapshot = lambda: DirectorySnapshot(
                                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 251, in __init__
    for p, st in self.walk(path):
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 258, in walk
    paths = [os.path.join(root, entry.name) for entry in self.listdir(root)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 258, in <listcomp>
    paths = [os.path.join(root, entry.name) for entry in self.listdir(root)]
                                ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

2025-02-04 21:42:01,578 INFO     MainThread __main__:main [main.py:121] Execution time:   81.44092560ms

**Comment by anetczuk** [comment]
Have You downgraded the watchdog? Exception goes from watchog, because newer version (starting from 2.2) is not backward compatible with older one I used during implementation. Of course, better solution would be fixing it in ClevoKeyboardControl, but for now You can try with older version of watchdog.

**Comment by OxoGhost01** [comment]
That's weird, when i look for watchdog on internet, it says the latest is 6.0.0 ; the version i can install when i use apt is 2.2.1-1. And when i try sudo apt install python3-watchdog=2.1.9 it returns 

Package python3-watchdog is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '2.1.9' for 'python3-watchdog' was not found

How can i downgrade it ?

**Comment by OxoGhost01** [comment]
I looked for it on debian tracker, but only these version are available : 

![Image](https://github.com/user-attachments/assets/70304f7e-3a2c-4ed9-8ff3-bfb777146b8e)

**Comment by anetczuk** [comment]
Just updated project source code to work with watchdog modern version (6.0.0). Try to run with changes.
